# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/boopiter',
                'doc_host': 'https://drscotthawley.github.io',
                'git_url': 'https://github.com/drscotthawley/boopiter',
                'lib_path': 'boopiter'},
  'syms': {'boopiter.core': {'boopiter.core.foo': ('core.html#foo', 'boopiter/core.py')}}}
