"""Fill in a module description here

Docs: https://drscotthawley.github.io/boopiter/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['launch']

# %% ../nbs/00_core.ipynb #da4d26dd
import subprocess, sys, time, urllib.request, urllib.error
from typing import Annotated
from fastcore.script import call_parse

def _port_owner(port):
    "Return 'boopiter' if boopiter answers on `port`, 'other' if something else does, None if nothing does."
    try:
        with urllib.request.urlopen(f'http://localhost:{port}/_boopiter_ping', timeout=1.0) as r:
            text = r.read().decode().strip()
        return 'boopiter' if text == 'boopiter' else 'other'
    except urllib.error.HTTPError:
        return 'other'   # got a real HTTP response, just not our ping -- something else is there
    except (ConnectionRefusedError, urllib.error.URLError):
        return None      # nothing is accepting connections there
    except Exception:
        return 'other'   # some other failure mode -- be conservative, don't touch it

def _kill_port(port):
    try:
        pids = subprocess.run(['lsof', '-ti', f'tcp:{port}'], capture_output=True, text=True).stdout.split()
    except FileNotFoundError:
        pids = []
    for pid in pids: subprocess.run(['kill', '-9', pid])
    if pids: time.sleep(0.3)

@call_parse
def launch(
    nbfile: Annotated[str, {'opt': False, 'nargs': '?'}] = None,  # .ipynb file to load on startup
    port: int = 8000,  # the port to serve boopiter on
):
    "Launch (or relaunch) the boopiter server; refuses to touch a port held by something that isn't boopiter"
    owner = _port_owner(port)
    if owner == 'other':
        print(f"Port {port} is already in use by something that isn't boopiter -- aborting.", file=sys.stderr)
        sys.exit(1)
    if owner == 'boopiter':
        print(f"Killing previous boopiter instance on port {port}...")
        _kill_port(port)
    if nbfile:
        from . import cells as _cells
        try:
            _cells.load_notebook(nbfile)
        except FileNotFoundError:
            print(f"No such notebook: {nbfile}", file=sys.stderr)
            sys.exit(1)
    import uvicorn
    uvicorn.run('boopiter.cells:app', host='0.0.0.0', port=port)
