"""The code-execution engine: a single shared IPython shell, plus the primitives that run a code cell's source and turn its stdout/stderr/rich-display output into an ordered list of output blocks -- both synchronously (`run_code`) and streamed from a background thread (`_run_code_bg` + `_RunState`/`_TeeStream`). Deliberately stateless about the notebook: no `nb`, no `_run_state` global, no rendering. `cells.py` owns those and drives these primitives.

Docs: https://drscotthawley.github.io/boopiter/kernel.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_kernel.ipynb.

# %% auto #0
__all__ = ['run_code']

# %% ../nbs/03_kernel.ipynb #kernelimports
import sys, base64, threading, io as _pyio
from toolslm.shell import get_shell
from IPython.utils.capture import capture_output

# %% ../nbs/03_kernel.ipynb #3e5ac46a
_shell = get_shell()
_shell.system = _shell.system_piped   # capture `!cmd` output into stdout

# get_shell() builds a standalone TerminalInteractiveShell without registering it as IPython's
# active instance -- so capture_output() (which looks up get_ipython() internally to find a shell
# to capture display() calls from) can't find it and silently skips rich-output capture entirely.
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell._instance = _shell

try:
    import matplotlib
    matplotlib.use('Agg')  # headless -- figures are captured explicitly in run_code(), not via any interactive/inline backend
except ImportError:
    pass

# IPython disables every rich MIME formatter but text/plain on a bare shell -- turn the ones we
# know how to render back on, so e.g. a DataFrame's _repr_html_ or a returned PIL Image gets used
# (both for display(...) calls and for the auto-formatted last expression; see run_code()).
_MIME_PRIORITY = ('text/html', 'image/svg+xml', 'image/png', 'text/markdown', 'application/json')
for _mime in _MIME_PRIORITY:
    if _mime in _shell.display_formatter.formatters:
        _shell.display_formatter.formatters[_mime].enabled = True

# %% ../nbs/03_kernel.ipynb #stdoutrtr1
class _StdoutRouter(_pyio.TextIOBase):
    "Installed once, at import time, as the process's real sys.stdout/sys.stderr. sys.stdout is inherently a single process-global object -- there's no such thing as a genuinely thread-local one -- so directly reassigning it (the old approach: `sys.stdout = _TeeStream(state)`, restored after) affects every thread for as long as it's swapped, not just the one running a background code cell. A concurrent write from the request-handling thread, another background run, or anything else landed in whichever cell's buffer happened to be installed at that moment. This router instead stays fixed as the actual global stream and dispatches each write() by looking up a per-thread registration (threading.local): whichever thread has bind()'d a target gets routed there; every other thread falls straight through to the real underlying stream, untouched. Reuse this bind()/unbind() pattern for any future background work that needs to capture its own stdout/stderr without cross-contaminating whatever else is running concurrently."
    _local = threading.local()

    def __init__(self, real):
        self._real = real

    def writable(self) -> bool: return True

    def write(self, s:str) -> int:
        target = getattr(self._local, 'target', None)
        return (target or self._real).write(s)

    def flush(self) -> None:
        target = getattr(self._local, 'target', None)
        (target if target is not None and hasattr(target, 'flush') else self._real).flush()

    def isatty(self) -> bool:
        "False while bound (matches _TeeStream's own isatty()==False, so tqdm etc. use '\\r'-style overwrites); delegates to the real stream otherwise, so terminal behavior outside a capture is unaffected."
        return False if getattr(self._local, 'target', None) is not None else self._real.isatty()

    @classmethod
    def bind(cls, target) -> None:
        "Route the CALLING thread's writes to `target` until unbind(). Only affects this thread -- every other thread keeps writing straight through to the real stream."
        cls._local.target = target

    @classmethod
    def unbind(cls) -> None:
        "Stop routing the calling thread's writes anywhere special -- back to the real stream."
        cls._local.target = None

_stdout_router, _stderr_router = _StdoutRouter(sys.stdout), _StdoutRouter(sys.stderr)
sys.stdout, sys.stderr = _stdout_router, _stderr_router

# %% ../nbs/03_kernel.ipynb #fa801f24
def _collapse_cr(s:str) -> str:
    "Collapse \\r-overwritten text (tqdm-style progress bars) down to each line's final state."
    return '\n'.join(ln.split('\r')[-1] for ln in s.split('\n'))

# %% ../nbs/03_kernel.ipynb #237ec61a
def _best_block(fmt:dict) -> dict:
    "The richest available rendering of a formatted-object MIME dict, as an output block; falls back to its plain-text repr."
    for mime in _MIME_PRIORITY:
        if mime in fmt:
            return {'type':'display', 'mime':mime, 'data':fmt[mime]}
    return {'type':'stream', 'mime':None, 'data':fmt.get('text/plain', '')}

# %% ../nbs/03_kernel.ipynb #aab4157f
def _flush_figures() -> list[dict]:
    "Any matplotlib figures left open after a cell runs, as image/png display blocks -- captured explicitly (savefig + close) rather than relying on an inline backend's event hooks, which proved unreliable on this headless shell."
    try:
        import matplotlib.pyplot as plt
    except ImportError:
        return []
    blocks = []
    for num in plt.get_fignums():
        fig = plt.figure(num)
        buf = _pyio.BytesIO()
        fig.savefig(buf, format='png', bbox_inches='tight')
        blocks.append({'type':'display', 'mime':'image/png', 'data':base64.b64encode(buf.getvalue()).decode()})
        plt.close(fig)
    return blocks

# %% ../nbs/03_kernel.ipynb #d45303a2
def run_code(src:str) -> list[dict]:
    "Execute `src` in the shared shell; return an ordered list of output blocks (each a dict with 'type' -- stream/error/display -- and, for display blocks, a 'mime' type). See Cell.output. Routes stdout/stderr through _StdoutRouter (same pattern as _run_code_bg) rather than IPython's own capture_output(stdout=True), whose internal swap is a raw global reassignment -- letting this call and a concurrent _run_code_bg (different threads) safely capture their own output at the same time instead of one clobbering the other's capture window."
    buffer:list[str] = []
    _StdoutRouter.bind(_TeeStream(buffer))
    try:
        with capture_output(stdout=False, stderr=False) as io:  # display()/last-expr capture only -- stdout/stderr are already routed to `buffer` above
            res = _shell.orig_run(src)  # bypass toolslm's run_cell wrapper -- it discards stderr and any display() output, keeping only stdout
    finally:
        _StdoutRouter.unbind()
    blocks = []
    if res.error_in_exec is not None:
        e = res.error_in_exec
        blocks.append({'type':'error', 'mime':None, 'data':f'{type(e).__name__}: {e}'})
    text = _collapse_cr(''.join(buffer))
    if text:
        blocks.append({'type':'stream', 'mime':None, 'data':text})
    blocks += [_best_block(o.data) for o in io.outputs]  # explicit display(...) calls, in call order
    if res.result is not None:
        fmt, _md = _shell.display_formatter.format(res.result)
        blocks.append(_best_block(fmt))
    blocks += _flush_figures()
    return blocks

# %% ../nbs/03_kernel.ipynb #b7b23d4c
class _RunState:
    "Tracks one in-flight background code-cell execution. Only one cell can run at a time (like a real kernel), so a single `_run_state` global is enough."
    def __init__(self, cell_id:int):
        self.cell_id = cell_id
        self.buffer:list[str] = []   # text chunks written so far, in arrival order
        self.done = False
        self.blocks:list[dict]|None = None
        self.thread:threading.Thread|None = None

# %% ../nbs/03_kernel.ipynb #fb206bb5
class _TeeStream(_pyio.TextIOBase):
    "A writable stream that appends every write() straight into `buffer` (a plain list of text chunks, in arrival order), so a poll request mid-execution can see output as it's produced -- unlike capture_output(), which only exposes text once its `with` block exits. Bound to the calling thread only via _StdoutRouter.bind() -- never assigned to sys.stdout/stderr directly. Subclassing TextIOBase (rather than a bare object) gives it a real isatty()/readable()/etc. file protocol -- without it, libraries like tqdm that probe for a proper file object fall back to appending a newline per update instead of overwriting in place with '\\r'."
    def __init__(self, buffer:list[str]): self.buffer = buffer
    def writable(self) -> bool: return True
    def write(self, s:str) -> int:
        if s: self.buffer.append(s)
        return len(s)

# %% ../nbs/03_kernel.ipynb #d05fcd2b
def _run_code_bg(src:str, state:_RunState) -> None:
    "Runs in a background thread: executes `src` with stdout/stderr tee'd into `state.buffer` as it goes, then fills in `state.blocks` (same shape as run_code()'s return) once execution finishes. See run_code_poll() for the other end. Binds this thread's output via _StdoutRouter -- NOT a raw sys.stdout/stderr reassignment -- so a concurrent write from any other thread (another background run, the request-handling thread, uvicorn's own logging) is never captured here by mistake; see _StdoutRouter."
    _StdoutRouter.bind(_TeeStream(state.buffer))
    try:
        with capture_output(stdout=False, stderr=False) as io:  # display()/last-expr capture only -- stdout/stderr are already routed to state.buffer above
            res = _shell.orig_run(src)
    finally:
        _StdoutRouter.unbind()
    blocks = []
    if res.error_in_exec is not None:
        e = res.error_in_exec
        blocks.append({'type':'error', 'mime':None, 'data':f'{type(e).__name__}: {e}'})
    text = _collapse_cr(''.join(state.buffer))
    if text:
        blocks.append({'type':'stream', 'mime':None, 'data':text})
    blocks += [_best_block(o.data) for o in io.outputs]
    if res.result is not None:
        fmt, _md = _shell.display_formatter.format(res.result)
        blocks.append(_best_block(fmt))
    blocks += _flush_figures()
    state.blocks = blocks
    state.done = True
