"""Generic LLM-calling utilities (models, prompting, tool schemas) -- deliberately kept independent of boopiter's own Notebook/Cell model, so this module never imports from `cells.py`. `cells.py` imports from here, never the other way around.

Docs: https://drscotthawley.github.io/boopiter/llms.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_llms.ipynb.

# %% auto #0
__all__ = ['get_tool_list', 'get_ollama_list', 'get_model_list', 'prompt_llm']

# %% ../nbs/02_llms.ipynb #5ea1e09b
from fastcore.utils import *
from lisette import *

# %% ../nbs/02_llms.ipynb #09d53f7e
# slmn (github.com/drscotthawley/slmn, a separate general-purpose toolkit -- see
# boopiter/pyproject.toml for the git dependency) is imported as plain modules here, not
# re-exported via `import *` -- see get_tool_list() below, which assembles actual tool
# functions on demand instead of merging namespaces.
import slmn.nbtools as _slmn_nbtools
import slmn.misc as _slmn_misc
import slmn.remote as _slmn_remote

# slmn.remote also has remote_launch/remote_status/remote_smoke_test, which can run arbitrary
# commands on a remote host over ssh -- a much bigger capability than the rest of slmn's tools.
# Least-privilege: don't hand those to the LLM by default, just the read-only/informational ones.
_SLMN_REMOTE_SAFE = ('fetch_url', 'check_ci', 'remote_gpu_free')

_LOCAL_TOOLS = []  # boopiter-defined tools always available, independent of slmn; empty for now, add as needed

# %% ../nbs/02_llms.ipynb #gettoollist1
def get_tool_list(include_slmn:bool=True # also include slmn's tools -- nbtools + misc (all of it) plus remote's safe/read-only subset (see _SLMN_REMOTE_SAFE; remote_launch/status/smoke_test, which can run arbitrary commands over ssh, are excluded from this default set)
                   ) -> list:
    "Assemble the list of tool functions to offer an LLM: boopiter's own local tools (_LOCAL_TOOLS, currently empty), plus by default most of what slmn publishes. Returns actual callables, not names -- pass straight to prompt_llm(tools=...). Per-notebook ad-hoc tools (see add_tool()) are layered on top of this by the caller, not included here."
    tools = list(_LOCAL_TOOLS)
    if include_slmn:
        for mod in (_slmn_nbtools, _slmn_misc):
            tools += [getattr(mod, name) for name in mod.__all__]
        tools += [getattr(_slmn_remote, name) for name in _SLMN_REMOTE_SAFE]
    return tools

# %% ../nbs/02_llms.ipynb #9df9b2f0
def get_ollama_list(): 
    "Get a list of supported ollama models; returns [] and warns if Ollama unavailable."
    import httpx, warnings
    try:
        models = httpx.get("http://localhost:11434/api/tags").json()
        return ['ollama/'+m['model'] for m in models.get('models', [])]
    except Exception as e:
        warnings.warn(f"Ollama not available: {e}")
        return []

# %% ../nbs/02_llms.ipynb #a2b64307
def get_model_list(): 
    "wrapper routine to get list of all available models from all sources"
    return get_ollama_list()  # TODO: add more model source, e.g. cloud, fileio

# %% ../nbs/02_llms.ipynb #b7fdcd9f
# lisette + local (Ollama) models: passing non-empty `tools=` combined with `tool_choice='none'`
# triggers a bug in litellm's MCP-handler codepath that returns a raw dict instead of a proper
# response object (AttributeError: 'dict' object has no attribute 'choices'). Same issue hit by
# SBrewer15/CellMate (https://github.com/SBrewer15/CellMate) -- this is their patch, adopted as-is:
# drop tool_schemas for just that one call whenever tool_choice=='none', then restore them after.
_orig_chat_call = Chat._call


# %% ../nbs/02_llms.ipynb #e7617fd4
@patch
def _call(self:Chat, msg:str|None=None, prefill:str|None=None, temp:float|None=None, think:str|None=None,
          search:str|None=None, stream:bool=False, max_steps:int=2, step:int=1, final_prompt:dict|None=None,
          tool_choice:str|None=None, max_tokens:int|None=None, **kwargs):
    "Internal method that always yields responses -- patched (see the comment above) to avoid a litellm/Ollama tool-calling bug."
    _orig_tools = self.tool_schemas
    if tool_choice == 'none': self.tool_schemas, tool_choice = None, None
    try: yield from _orig_chat_call(self, msg, prefill, temp, think, search, stream, max_steps, step, final_prompt, tool_choice, max_tokens, **kwargs)
    finally: self.tool_schemas = _orig_tools

# %% ../nbs/02_llms.ipynb #834cf2bc
def _reply_details_html(response, msg) -> str:
    "A collapsible <details> block summarizing an LLM call's metadata (model, finish reason, token counts, tool calls, reasoning) -- not part of the reply's actual content, kept out of Cell.source (see Cell.details) so it's never sent back to the model as context, and shown collapsed, in gray, above the real text. onclick=stopPropagation keeps a click on <summary> from also bubbling into the cell's click-anywhere-to-edit handler."
    u = response.usage
    rows = [('Model', response.model), ('Finish reason', response.choices[0].finish_reason)]
    if u: rows.append(('Tokens', f'{u.prompt_tokens} prompt + {u.completion_tokens} completion = {u.total_tokens} total'))
    if msg.tool_calls: rows.append(('Tool calls', ', '.join(tc.function.name for tc in msg.tool_calls)))
    items = ''.join(f'<li>{k}: {v}</li>' for k, v in rows)
    reasoning = f'<pre style="white-space:pre-wrap">{msg.reasoning_content}</pre>' if getattr(msg, 'reasoning_content', None) else ''
    return (f'<details class="text-gray-400" onclick="event.stopPropagation()"><summary>Reply details</summary>'
            f'<ul>{items}</ul>{reasoning}</details>')

def prompt_llm(context:str, model:str='ollama/qwen2.5-coder:latest', tools:list|None=None) -> tuple[str,str]:
    "Send a prompt to the LLM; returns (content, details_html) -- the reply text itself, and a separate collapsible <details> block of call metadata (model/tokens/finish reason/reasoning) meant to be stored apart from the reply (see Cell.details), not mixed into it. TODO: can we stream the response rather than wait for as a final big chunk?"
    # _skip_mcp_handler avoids litellm's MCP-proxy import chain (needs fastapi/orjson) that we don't use.
    # Drop it (and re-add fastapi/orjson to pyproject.toml) if/when we actually want MCP tool support.
    chat = Chat(model, tools=tools or [], callkw={'_skip_mcp_handler': True}) # FYI: this makes a fresh stateless context each time. is that what we want?
    response = chat(context)
    msg = contents(response)
    return msg.content, _reply_details_html(response, msg)


# %% ../nbs/02_llms.ipynb #c7bc561b
_PREFERRED_MODEL_SUBSTR = 'qwen2.5-coder'  # used if present, regardless of exact tag/version

