"""Just following SolveIt Course 2 Lesson 4 & 5: "Creating SolveIt in SolveIt",

Docs: https://drscotthawley.github.io/boopiter/lesson.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_lesson.ipynb.

# %% auto #0
__all__ = ['daisy_hdrs', 'app', 'rt', 'p', 'get_preview', 'Button', 'Input']

# %% ../nbs/01_lesson.ipynb #da4d26dd
from fastcore.utils import *
from fasthtml.common import *
from fasthtml.jupyter import *
from fastlite import * 
import fasthtml.components as fh
import httpx

# %% ../nbs/01_lesson.ipynb #b857565f-2a3b-4bee-b2c7-139a4b5b4bba
daisy_hdrs = [
    Link(href='https://cdn.jsdelivr.net/npm/daisyui@5', rel='stylesheet', type='text/css'),
    Script(src='https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4')
]

# %% ../nbs/01_lesson.ipynb #56d2e19e-c0d5-4cea-82e0-4050d96fc310
app = FastHTML(hdrs=daisy_hdrs)
rt = app.route

# %% ../nbs/01_lesson.ipynb #8a3ed243-18be-49c9-9e3e-a335a18cd8ce
def get_preview(app): return partial(HTMX, app=app, host=None, port=None)

# %% ../nbs/01_lesson.ipynb #0d1e2746-aec9-4ccd-bf75-c3ea3648facb
p = get_preview(app)

# %% ../nbs/01_lesson.ipynb #c45cb58e-1e89-4168-8471-2a956d6e8dbc
def Button(*c, cls='', **kw): 
    return fh.Button(*c, cls=f'btn {cls}', **kw)

def Input(*c, cls='', **kw): 
    return fh.Input(*c, cls=f'input {cls}', **kw)
